version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=calendar
      - POSTGRES_PASSWORD=calendar
      - POSTGRES_DB=calendar

  rabbit: 
    image: rabbitmq:3.9.11-management
    ports:
      - "5672:5672"
      - "15672:15672"